#ifdef UXNA_TEST

/* Neurai address families against a Neurai-DePIN regtest node (-pqwallet=1):
 *
 *   family       witver  HRP (main / test)  scriptPubKey
 *   AuthScript     1     nc   / tnc         51 20 <C>
 *   PQ (strict)    2     pq   / tpq         52 20 <C>
 *   ECDSA (strict) 3     nq   / tnq         53 20 <C>
 *
 * NODE_* values were produced by the node itself: `getnewaddress "" pq`,
 * `getnewaddress "" ecdsa`, `getnewaddress` (generic v1) and `dumpprivkey`
 * for the keys. The v1 address of the PQ key is reported `ismine` by the same
 * node's `validateaddress`. Mainnet forms are the same programs under the
 * mainnet HRPs.
 */

#include <string.h>
#include "minunit.h"
#include "Neurai.h"
#include "NeuraiPQ.h"
#include "Networks.h"
#include "Conversion.h"

using std::string;

/* Raw ML-DSA-44 public key (1312 B) of the node's `getnewaddress "" pq` key. */
static const char NODE_PQ_PUBKEY_HEX[] =
    "556270eef4f15254ead0968e2de14c4bd6ae9f0467ff073842fbb4e2c49e3f4e"
    "39c1636ca5703e2b7755e5bc05d66b5ef6adc5fdbdfbbcd1b3ee54b9e879fe60"
    "4bfbc42da0957795bcbc0bccd091e390ca9efb1ade2d15831f5ffaa0b1eabce7"
    "df1b0caae239cfcf682bb172b2f92726ef1e98900505dda7818c60420f13e13d"
    "6cdf585c74ccaf1bd3c2458b7bfb87b5e7431d4e1f12d80f61046e607620228d"
    "96e63999a288f7c9e2375e7467f48070fc9b65829fcaaa39bacbe612181c3be2"
    "be6f61e76436910cf2024ff241d692924fae13866582cb71f39333b131320598"
    "4f0edd1176cb27b7547a9e721775e101eecc6e2d6bd30d4328e4e5d4fd99c3fb"
    "be5d227f68a9575929a6b839080ba8cf58c628bf3f6e6763524f56a0a5d53d18"
    "547a4832548c10e402bbc53a03c2e274a87f8ef8866187a7477826d35a0b13e1"
    "05c0ca6af4a34e529c9174fee36481ceebe1040f8f3cff7c6ab6ba2bf2c10580"
    "1bb1e33dda677452c356a1da82561a72f69e66af17ca991b9ee4147341aa1cbe"
    "dc985535a4a71f89bc6f33353e7074d72942861f749e5b240e9417ee9e78bb1e"
    "474b15cde7ad78abae031222d3754e55cd8cda66df0d91acab457708ccffb6dc"
    "eb604836297fa1768c10aca555d9f5a69550abafd5d533b454367e01c5cec270"
    "6a22df7f22ada7ed1d941cc54af924da1c04a08602286fe1689e9fb744d7dfcf"
    "138f32dd4e482f6bf6a2925bf0a0aedc155b4e8eede97f8b6d54b584698b2203"
    "a4a2e02fc4801170d3a3a62aeba47441bd16ecff54977bf6491f4f7bec46090b"
    "a71867450e3442bf9009023e0fcaa538990dc2c41474ea4ce2065a0561d104db"
    "93f08f8f70e23d1ffe80da5c3dee92cf9dccbcf122d6cb397b3c20aa234a1366"
    "40e9defd0d41ffb2a1ad525e6f150f64d77a0254a8101c9cdc0815dbde9c5e9f"
    "0f8c2bb6679f14fe810ed12431bba183e116b03f4a3db91df462385e879b7a7b"
    "824fb18eb4e2e133234266977e42e3264740691e81732926c5561aa92b6e3542"
    "7829ef1d89e11098ce719fc4eccdd71efaf5cb9ef8f60e21a5eb89966235db34"
    "332fc8172eb908d31e1b441c6ce87f4cfce774487195ee568d05c8197aed6103"
    "45f8fbda3344377e022ca8664b27f6e9150047ba32840076d3f0b4b249c87455"
    "b479a2c6a516398011b744fa7ad7fe42e033536f2c134760d8b7dda6c602d90d"
    "60a9ba55d80acba0e8e6404bef36619089e32170a21af72ab5b6518626b7dbc7"
    "0c2365288321e36fd05b634a2779ba206ab0a9f670163da96714dcb80c5ba51d"
    "1763aa36582d8ff980f60e01ea8cad6b3f038b14cded4fae8d724ec657047212"
    "34ffc895791d80a9c0026545dd9a5a4307845337266bf3901227635f6ba0d0b1"
    "29036ea623808b237bbaaa13e1051075e09753b05f70a3fdc9c404e471276802"
    "1ecdd70c44345223420015a5a0de04b1c8b5930bdca21c10ef42b5799a4b3d69"
    "97889eee923bba9bf0884b915cee401ae95238c857cfd2712698b9e6e1992bdc"
    "c33ce519905cec202a126a877c8f5e7c5f79915cea24f83679b201898294f361"
    "ae9d0537c5c759dbb61d4b2b86a80edcbcfe0a6452d9a92fdd542e1670994700"
    "8e57a88e50d3562a410c71318e06e9cdded13dcf55a74423efaffe02329b8e58"
    "1d50a3e989a10aa212ba778c97549759734223b9ecbbce487b7ab39f24225b52"
    "ac1e4112d5f7a415f6ddef8b39a51513d2110d6f196578683cbaa05ef5930d3d"
    "392ebb46351c4b7d0591d2aea117ebdf1505d52833965be46cc6a115e99fd626"
    "489adea88fafa6c4135ce006900fc040fd1653de00487fb7a96862044236db49";

/* Strict PQ v2 address generated by the node for that key. */
static const char NODE_PQ_V2_ADDRESS[] = "tpq1z26xe87v03dum5sugz0h5sdwhur6kftsn9ccl9f6agsdp7atcgyaqdex2vu";
static const char NODE_PQ_V2_SPK[] =
    "5220568d93f98f8b79ba438813ef4835d7e0f564ae132e31f2a75d441a1f7578413a";
static const char NODE_PQ_V2_MAINNET[] = "pq1z26xe87v03dum5sugz0h5sdwhur6kftsn9ccl9f6agsdp7atcgyaqvq5dan";

/* Generic v1 address of the same key (authType 0x01, witnessScript OP_TRUE). */
static const char NODE_PQ_V1_ADDRESS[] = "tnc1pt6jvutcswz23w983vtlp0w3kt4a6hwfgctw396u3jl73c9f6uumqz5eps9";
static const char NODE_PQ_V1_SPK[] =
    "51205ea4ce2f1070951714f162fe17ba365d7babb928c2dd12eb9197fd1c153ae736";
static const char NODE_PQ_V1_MAINNET[] = "nc1pt6jvutcswz23w983vtlp0w3kt4a6hwfgctw396u3jl73c9f6uumqrdtxp2";

/* Strict ECDSA v3: key of the node's `getnewaddress "" ecdsa` (dumpprivkey). */
static const char NODE_EC_WIF[] = "cQD6aaT9qYrdPEGnek4F3RSwWmCpUTZGudhvyh46A55dqH6ikugC";
static const char NODE_EC_PUBKEY_HEX[] =
    "03c686edd6a7df742a8bf13daf7d992c39ecc38ad2e503c67dc5c9177dc66db991";
static const char NODE_EC_V3_ADDRESS[] = "tnq1rskqpx9d5ccaj8eplrz7rlp9ds5w9wpppmqgenvmzeflmlme8p6yqgl0c8d";
static const char NODE_EC_V3_SPK[] =
    "532085801315b4c63b23e43f18bc3f84ad851c570421d81199b362ca7fbfef270e88";
static const char NODE_EC_V3_MAINNET[] = "nq1rskqpx9d5ccaj8eplrz7rlp9ds5w9wpppmqgenvmzeflmlme8p6yqfxalkz";
/* The same key as Base58 P2PKH (node `validateaddress` ismine). */
static const char NODE_EC_P2PKH[] = "tRATqx227pog5df6cWrgP9gecLr41mEw7u";

/* A generic v1 address from the node's plain `getnewaddress`. */
static const char NODE_V1_ADDRESS[] = "tnc1pvjuphw3cy9r2wsx4v7s7vjed2kyt9465jp630yalqwppjgsvr7yqhrszer";
static const char NODE_V1_SPK[] =
    "512064b81bba382146a740d567a1e64b2d5588b2d75490751793bf038219220c1f88";

/* Rejected by the node's validateaddress: the HRP fixes the witness version.
 * OLD_V1 is NODE_V1_ADDRESS in the pre-0.1.0 "tnq1p…" encoding. */
static const char OLD_V1_ADDRESS[] = "tnq1pvjuphw3cy9r2wsx4v7s7vjed2kyt9465jp630yalqwppjgsvr7yq9hf7sp";
static const char BAD_V1_UNDER_PQ[] = "tpq1pt6jvutcswz23w983vtlp0w3kt4a6hwfgctw396u3jl73c9f6uumqwxmrr7";
static const char BAD_V2_UNDER_NC[] = "tnc1zt6jvutcswz23w983vtlp0w3kt4a6hwfgctw396u3jl73c9f6uumq2fqw7w";
static const char BAD_V2_UNDER_NQ[] = "tnq1zt6jvutcswz23w983vtlp0w3kt4a6hwfgctw396u3jl73c9f6uumqcaejhv";

/* Mainnet Base58 P2PKH addresses whose lower-cased prefix looks like a
 * Bech32m HRP ("nq1" / "nc1"): they must still decode as P2PKH. */
static const char P2PKH_NQ1_LOOKALIKE[] = "NQ1W1111111111111111111111111Br3xa";
static const char P2PKH_NC1_LOOKALIKE[] = "Nc1W1111111111111111111111112hGBcX";

static uint8_t pqPub[UNEURAI_PQ_PUBKEY_RAW_LEN];

static void loadPqPub(){
    size_t n = fromHex(NODE_PQ_PUBKEY_HEX, sizeof(NODE_PQ_PUBKEY_HEX) - 1, pqPub, sizeof(pqPub));
    mu_assert_int_eq(UNEURAI_PQ_PUBKEY_RAW_LEN, (int)n);
}

/* minunit reads its string arguments after the full expression, so a
 * temporary std::string's c_str() would dangle: keep a copy alive. */
static const char * hold(const string & v){
    static char ring[4][256];
    static int next = 0;
    char * slot = ring[next];
    next = (next + 1) % 4;
    strncpy(slot, v.c_str(), 255);
    slot[255] = '\0';
    return slot;
}

static const char * scriptHex(const Script & s){
    return hold(toHex(s.scriptArray, s.scriptLen));
}

MU_TEST(test_hrp_table){
    mu_assert_string_eq("nc",  authScriptHrp(1, false));
    mu_assert_string_eq("tnc", authScriptHrp(1, true));
    mu_assert_string_eq("pq",  authScriptHrp(2, false));
    mu_assert_string_eq("tpq", authScriptHrp(2, true));
    mu_assert_string_eq("nq",  authScriptHrp(3, false));
    mu_assert_string_eq("tnq", authScriptHrp(3, true));
    mu_check(authScriptHrp(0, false) == NULL);
    mu_check(authScriptHrp(4, true) == NULL);
    mu_assert_string_eq("nc",  NeuraiPQ.bech32);
    mu_assert_string_eq("tnc", NeuraiPQTest.bech32);
    mu_assert_int_eq(1, NeuraiPQ.witnessVersion);
    mu_assert_string_eq("pq",  NeuraiPQV2.bech32);
    mu_assert_string_eq("tpq", NeuraiPQV2Test.bech32);
    mu_assert_int_eq(2, NeuraiPQV2Test.witnessVersion);
    mu_check(&NeuraiPQV1 == &NeuraiPQ);
    mu_check(&NeuraiPQV1Test == &NeuraiPQTest);
    mu_assert_int_eq(2, strictAuthScriptWitnessVersion(UNEURAI_AUTHTYPE_PQ));
    mu_assert_int_eq(3, strictAuthScriptWitnessVersion(UNEURAI_AUTHTYPE_ECDSA));
    mu_assert_int_eq(0, strictAuthScriptWitnessVersion(UNEURAI_AUTHTYPE_NOAUTH));
    mu_assert_int_eq(UNEURAI_AUTHTYPE_PQ, strictAuthScriptAuthType(2));
    mu_assert_int_eq(UNEURAI_AUTHTYPE_ECDSA, strictAuthScriptAuthType(3));
    mu_assert_int_eq(0, strictAuthScriptAuthType(1));
}

MU_TEST(test_pq_key_v1_and_v2_addresses_match_node){
    loadPqPub();
    char addr[UNEURAI_AUTHSCRIPT_ADDRESS_MAX] = {0};
    mu_check(pqAddressFromPubKey(&NeuraiPQV2Test, pqPub, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_PQ_V2_ADDRESS, addr);
    mu_check(pqAddressFromPubKey(&NeuraiPQV2, pqPub, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_PQ_V2_MAINNET, addr);
    mu_check(pqAddressFromPubKey(&NeuraiPQTest, pqPub, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_PQ_V1_ADDRESS, addr);
    mu_check(pqAddressFromPubKey(&NeuraiPQ, pqPub, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_PQ_V1_MAINNET, addr);

    /* The versioned commitment is the program of the node's scriptPubKey. */
    const uint8_t ws[1] = { 0x51 };
    uint8_t c[32], spk[34];
    mu_assert_int_eq(1, buildVersionedAuthScriptCommitment(2, UNEURAI_AUTHTYPE_PQ, pqPub, sizeof(pqPub), ws, 1, c));
    mu_assert_int_eq(34, (int)buildVersionedAuthScriptScriptPubKey(2, c, spk, sizeof(spk)));
    mu_assert_string_eq(NODE_PQ_V2_SPK, hold(toHex(spk, 34)));
    mu_assert_int_eq(1, buildAuthScriptCommitment(UNEURAI_AUTHTYPE_PQ, pqPub, sizeof(pqPub), ws, 1, c));
    mu_assert_int_eq(34, (int)buildAuthScriptScriptPubKey(c, spk, sizeof(spk)));
    mu_assert_string_eq(NODE_PQ_V1_SPK, hold(toHex(spk, 34)));
}

MU_TEST(test_strict_commitment_rejects_non_template){
    loadPqPub();
    uint8_t c[32];
    const uint8_t ws51[1] = { 0x51 };
    const uint8_t ws52[1] = { 0x52 };
    /* v2 needs authType 0x01 and witnessScript exactly OP_TRUE. */
    mu_assert_int_eq(0, buildVersionedAuthScriptCommitment(2, UNEURAI_AUTHTYPE_PQ, pqPub, sizeof(pqPub), ws52, 1, c));
    mu_assert_int_eq(0, buildVersionedAuthScriptCommitment(2, UNEURAI_AUTHTYPE_NOAUTH, NULL, 0, ws51, 1, c));
    /* v3 needs authType 0x02 and a compressed key. */
    uint8_t ec[33];
    fromHex(NODE_EC_PUBKEY_HEX, ec, sizeof(ec));
    mu_assert_int_eq(0, buildVersionedAuthScriptCommitment(3, UNEURAI_AUTHTYPE_PQ, pqPub, sizeof(pqPub), ws51, 1, c));
    mu_assert_int_eq(1, buildVersionedAuthScriptCommitment(3, UNEURAI_AUTHTYPE_ECDSA, ec, 33, ws51, 1, c));
    uint8_t notCompressed[33];
    memcpy(notCompressed, ec, 33);
    notCompressed[0] = 0x04;
    mu_assert_int_eq(0, buildVersionedAuthScriptCommitment(3, UNEURAI_AUTHTYPE_ECDSA, notCompressed, 33, ws51, 1, c));
    /* Only witness versions 1..3 have an address family. */
    mu_assert_int_eq(0, buildVersionedAuthScriptCommitment(4, UNEURAI_AUTHTYPE_PQ, pqPub, sizeof(pqPub), ws51, 1, c));
    uint8_t spk[34];
    mu_assert_int_eq(0, (int)buildVersionedAuthScriptScriptPubKey(0, c, spk, sizeof(spk)));
    mu_assert_int_eq(0, (int)buildVersionedAuthScriptScriptPubKey(4, c, spk, sizeof(spk)));
}

MU_TEST(test_ecdsa_v3_address_matches_node){
    uint8_t ec[33];
    mu_assert_int_eq(33, (int)fromHex(NODE_EC_PUBKEY_HEX, ec, sizeof(ec)));
    char addr[UNEURAI_AUTHSCRIPT_ADDRESS_MAX] = {0};
    mu_check(ecdsaAddressFromPubKey(ec, true, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_EC_V3_ADDRESS, addr);
    mu_check(ecdsaAddressFromPubKey(ec, false, addr, sizeof(addr)) > 0);
    mu_assert_string_eq(NODE_EC_V3_MAINNET, addr);

    /* PublicKey / PrivateKey helpers (WIF selects NeuraiTest). */
    PrivateKey pk(NODE_EC_WIF);
    mu_assert_string_eq(NODE_EC_PUBKEY_HEX, hold(pk.publicKey().toString()));
    mu_assert_string_eq(NODE_EC_V3_ADDRESS, hold(pk.ecdsaAddress()));
    mu_assert_string_eq(NODE_EC_P2PKH, hold(pk.legacyAddress()));
    mu_assert_string_eq(NODE_EC_V3_ADDRESS, hold(pk.publicKey().ecdsaAddress(&NeuraiTest)));
    mu_assert_string_eq(NODE_EC_V3_MAINNET, hold(pk.publicKey().ecdsaAddress(&Neurai)));
    mu_assert_string_eq(NODE_EC_V3_MAINNET, hold(pk.publicKey().ecdsaAddress(&NeuraiLegacy)));

    /* An uncompressed PublicKey still commits to its compressed form. */
    PublicKey uncompressed = pk.publicKey();
    uncompressed.compressed = false;
    mu_assert_string_eq(NODE_EC_V3_ADDRESS, hold(uncompressed.ecdsaAddress(&NeuraiTest)));

    /* Script(pubkey, P2AUTHSCRIPT_V3) is the node's scriptPubKey. */
    Script s(pk.publicKey(), P2AUTHSCRIPT_V3);
    mu_assert_string_eq(NODE_EC_V3_SPK, scriptHex(s));
    mu_check(s.type() == P2AUTHSCRIPT_V3);
    mu_assert_int_eq(3, s.authScriptVersion());
}

/* @neuraiproject/neurai-key 5.0.1 for the oracle mnemonic:
 *   getAddressByPath("xna",      …, "m/84'/1900'/0'/0/0")
 *   getAddressByPath("xna-test", …, "m/84'/1'/0'/0/0")
 *   getAddressByPath("xna-legacy", …, "m/44'/1900'/0'/0/0") */
static const char KEY5_MNEMONIC[] =
    "result pact model attract result puzzle final boss private educate luggage era";
static const char KEY5_XNA[]        = "nq1rp2ggnqzc6tuflpvl8y546y47k267q8044kzc5p4t63h6ygry0trqsdg6zs";
static const char KEY5_XNA_TEST[]   = "tnq1rgyglqrnncwfqx594um7f5hl3nj33w0mgax7qeuskaaxmtszjk0fsz0jvty";
static const char KEY5_XNA_LEGACY[] = "NWeC9vTbTHJXMJyWt93CVeD8HQYjc4HMwt";

MU_TEST(test_hd_paths_match_neurai_key_5){
    HDPrivateKey root(KEY5_MNEMONIC, "");
    HDPrivateKey xna = root.derive("m/84'/1900'/0'/0/0");
    mu_assert_string_eq(KEY5_XNA, hold(xna.ecdsaAddress()));
    HDPrivateKey legacy = root.derive("m/44'/1900'/0'/0/0");
    mu_assert_string_eq(KEY5_XNA_LEGACY, hold(legacy.legacyAddress()));

    HDPrivateKey rootTest(KEY5_MNEMONIC, "", &NeuraiTest);
    HDPrivateKey xnaTest = rootTest.derive("m/84'/1'/0'/0/0");
    mu_assert_string_eq(KEY5_XNA_TEST, hold(xnaTest.ecdsaAddress()));
}

MU_TEST(test_decode_every_family){
    struct { const char * addr; const char * spk; uint8_t ver; bool testnet; ScriptType type; } v[] = {
        { NODE_V1_ADDRESS,     NODE_V1_SPK,    1, true,  P2AUTHSCRIPT    },
        { NODE_PQ_V1_MAINNET,  NODE_PQ_V1_SPK, 1, false, P2AUTHSCRIPT    },
        { NODE_PQ_V2_ADDRESS,  NODE_PQ_V2_SPK, 2, true,  P2AUTHSCRIPT_V2 },
        { NODE_PQ_V2_MAINNET,  NODE_PQ_V2_SPK, 2, false, P2AUTHSCRIPT_V2 },
        { NODE_EC_V3_ADDRESS,  NODE_EC_V3_SPK, 3, true,  P2AUTHSCRIPT_V3 },
        { NODE_EC_V3_MAINNET,  NODE_EC_V3_SPK, 3, false, P2AUTHSCRIPT_V3 },
    };
    for(size_t i = 0; i < sizeof(v) / sizeof(v[0]); i++){
        uint8_t ver = 0, prog[32];
        bool testnet = !v[i].testnet;
        mu_assert_int_eq(1, authScriptAddressDecode(v[i].addr, &ver, &testnet, prog));
        mu_assert_int_eq(v[i].ver, ver);
        mu_check(testnet == v[i].testnet);
        mu_assert_string_eq(v[i].spk + 4, hold(toHex(prog, 32)));

        /* Script(address) builds the node's scriptPubKey … */
        Script s(v[i].addr);
        mu_assert_string_eq(v[i].spk, scriptHex(s));
        mu_check(s.type() == v[i].type);
        mu_assert_int_eq(v[i].ver, s.authScriptVersion());
        mu_assert_int_eq(v[i].ver, authScriptWitnessVersionOf(s.scriptArray, s.scriptLen));

        /* … and renders back to the same address through both overloads. */
        const ChainNetwork * net = v[i].testnet ? &NeuraiTest : &Neurai;
        mu_assert_string_eq(v[i].addr, hold(s.address(net)));
        const ChainNetworkPQ * pqNet = v[i].testnet ? &NeuraiPQTest : &NeuraiPQ;
        mu_assert_string_eq(v[i].addr, hold(s.address(pqNet)));
        const ChainNetworkPQ * pqNetV2 = v[i].testnet ? &NeuraiPQV2Test : &NeuraiPQV2;
        mu_assert_string_eq(v[i].addr, hold(s.address(pqNetV2)));

        /* TxOut(address) routes through the same decoder. */
        TxOut out(v[i].addr, 1000);
        mu_assert_string_eq(v[i].spk, scriptHex(out.scriptPubkey));
    }
}

MU_TEST(test_decode_uppercase){
    char upper[UNEURAI_AUTHSCRIPT_ADDRESS_MAX] = {0};
    for(size_t i = 0; i < strlen(NODE_EC_V3_ADDRESS); i++){
        char c = NODE_EC_V3_ADDRESS[i];
        upper[i] = (c >= 'a' && c <= 'z') ? (char)(c - 'a' + 'A') : c;
    }
    Script s(upper);
    mu_assert_string_eq(NODE_EC_V3_SPK, scriptHex(s));
}

MU_TEST(test_non_canonical_pairs_rejected){
    const char * bad[] = { OLD_V1_ADDRESS, BAD_V1_UNDER_PQ, BAD_V2_UNDER_NC, BAD_V2_UNDER_NQ };
    for(size_t i = 0; i < sizeof(bad) / sizeof(bad[0]); i++){
        uint8_t ver = 0, prog[32];
        mu_assert_int_eq(0, authScriptAddressDecode(bad[i], &ver, NULL, prog));
        Script s(bad[i]);
        mu_assert_int_eq(0, (int)s.scriptLen);
    }
    /* The old encoding no longer decodes under the v1 networks either. */
    uint8_t c[32];
    mu_assert_int_eq(0, pqAddressDecode(OLD_V1_ADDRESS, &NeuraiPQTest, c));
    mu_assert_int_eq(1, pqAddressDecode(NODE_V1_ADDRESS, &NeuraiPQTest, c));
    mu_assert_string_eq(NODE_V1_SPK + 4, hold(toHex(c, 32)));
    /* pqAddressDecode is family-specific. */
    mu_assert_int_eq(0, pqAddressDecode(NODE_PQ_V2_ADDRESS, &NeuraiPQTest, c));
    mu_assert_int_eq(1, pqAddressDecode(NODE_PQ_V2_ADDRESS, &NeuraiPQV2Test, c));
    mu_assert_int_eq(0, pqAddressDecode(NODE_PQ_V2_ADDRESS, &NeuraiPQV2, c));
}

MU_TEST(test_base58_lookalikes_stay_p2pkh){
    /* Bech32m is tried first, but a Base58 string never has a valid Bech32m
     * checksum, so these still decode as P2PKH. */
    Script a(P2PKH_NQ1_LOOKALIKE);
    mu_check(a.type() == P2PKH);
    mu_assert_string_eq(P2PKH_NQ1_LOOKALIKE, hold(a.address(&Neurai)));
    Script b(P2PKH_NC1_LOOKALIKE);
    mu_check(b.type() == P2PKH);
    Script c(NODE_EC_P2PKH);
    mu_check(c.type() == P2PKH);
    mu_assert_string_eq(NODE_EC_P2PKH, hold(c.address(&NeuraiTest)));
}

MU_TEST(test_witness_version_of_asset_wrapped_script){
    uint8_t spk[40];
    size_t n = fromHex(NODE_EC_V3_SPK, spk, sizeof(spk));
    mu_assert_int_eq(34, (int)n);
    spk[34] = 0xc0; /* OP_XNA_ASSET … */
    mu_assert_int_eq(3, authScriptWitnessVersionOf(spk, 35));
    spk[34] = 0x75; /* anything else after the program is not an AuthScript output */
    mu_assert_int_eq(0, authScriptWitnessVersionOf(spk, 35));
    spk[0] = 0x54;  /* OP_4 */
    mu_assert_int_eq(0, authScriptWitnessVersionOf(spk, 34));
}

MU_TEST_SUITE(test_suite){
    MU_RUN_TEST(test_hrp_table);
    MU_RUN_TEST(test_pq_key_v1_and_v2_addresses_match_node);
    MU_RUN_TEST(test_strict_commitment_rejects_non_template);
    MU_RUN_TEST(test_ecdsa_v3_address_matches_node);
    MU_RUN_TEST(test_hd_paths_match_neurai_key_5);
    MU_RUN_TEST(test_decode_every_family);
    MU_RUN_TEST(test_decode_uppercase);
    MU_RUN_TEST(test_non_canonical_pairs_rejected);
    MU_RUN_TEST(test_base58_lookalikes_stay_p2pkh);
    MU_RUN_TEST(test_witness_version_of_asset_wrapped_script);
}

int main(int argc, char *argv[]){
    MU_RUN_SUITE(test_suite);
    MU_REPORT();
    return MU_EXIT_CODE;
}

#endif
